package practice;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;
public class autogeneratednostring {
	
//	class employee
	
		String name;
		int no;
		final static String job="developer";
		static int idn=1;
		int id;
	InputStreamReader r= new InputStreamReader(System.in);
	BufferedReader br= new BufferedReader(r);
	//String a =br.readLine();
	autogeneratednostring()throws IOException
	{
	 name =br.readLine();
	 no= Integer.parseInt(br.readLine());	
	 id=idn++;
	}
	autogeneratednostring(int i, String na)
	{
		no=i;
		name=na;
		//id++;
	}
	void disp()
	{
	System.out.println("name is:"+name);
	System.out.println("no is:"+no);
	System.out.println("designation is:"+job);
	System.out.println("id is:"+id);

	}
	public static void main(String ar[]) throws IOException
	{
		//employee s1 =new employee(90,"oupjeet");
		autogeneratednostring s2=new autogeneratednostring();
		autogeneratednostring s3=new autogeneratednostring();
		
		//s1.disp();
		s2.disp();
		s3.disp();
		
	}
	}


